allowBuilds:
  esbuild: false
  sharp: false
minimumReleaseAgeExclude:
  - astro@6.4.7 || 6.4.8 || 7.0.2 || 7.1.4
  - live-photo@0.1.0 || 0.2.0
  - '@astrojs/markdown-satteri@0.3.2'
  - '@astrojs/check@0.9.10'
  - '@astrojs/mdx@7.0.4'
